export type { Figure, Link } from './common'
export type { Education, Portrait, Profile, Social } from './profile'
export type { Decision, System } from './system'
export type { EngineeringGroup, Experience } from './experience'
export type { Note } from './note'
export type { Project } from './project'
export type { Research, ResearchKind } from './research'
export { isResearchKind, RESEARCH_KINDS } from './research'
export type { SectionCopy } from './section'
export { isSectionId } from './section'
